// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiredBrainCoffee.CustomersApp.Data;

#nullable disable

namespace WiredBrainCoffee.CustomersApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251104083710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WiredBrainCoffee.CustomersApp.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Julia",
                            IsDeveloper = true,
                            LastName = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Anna",
                            IsDeveloper = false,
                            LastName = "Tester"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Thomas",
                            IsDeveloper = false,
                            LastName = "Manager"
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.CustomersApp.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Strong black coffee",
                            Name = "Espresso"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Espresso with steamed milk and foam",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Espresso with lots of steamed milk",
                            Name = "Latte"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Espresso with hot water",
                            Name = "Americano"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chocolate flavored coffee drink",
                            Name = "Mocha"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Coffee steeped in cold water",
                            Name = "Cold Brew"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Espresso marked with foam",
                            Name = "Macchiato"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
